# Generated by Django 5.2.1 on 2025-05-28 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('author', models.TextField()),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image_url', models.CharField(default='blog/images/blog.jpg', max_length=200)),
            ],
        ),
    ]
