# Generated by Django 5.2.1 on 2025-05-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_author_first_name_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.CharField(default='blog/images/blog1.jpg', max_length=200),
        ),
    ]
